### ISSUE TITLE
[BUG]: No way to copy the contents from a directory of a repository to another repository with same structure

### ISSUE THREAD

**Issue by AshutoshBeta** [octokit/rest.js#279] opened 2023-03-31 06:19 UTC
### What happened?

There is no way to create a directory using Octokit:
It only creates files but when a repository has directories and subdirectories it doesn't create that
```
const response = await octokitClient.rest.repos.createOrUpdateFileContents({
                owner: owner,
                repo: repoResponse?.data?.name,
                path: `${item.name}`,
                message: `Import ${item.name} from ${sourceRepo}`,
                content: fileContents.data.content,
                sha: fileContents.data.sha,
              });
```

### Versions

"octokit": "^2.0.14"

### Relevant log output

```shell
Even the directories inside the repository are created as a file
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment] 2023-04-10 20:47
This may be an intended behavior of Git. See [here](https://archive.kernel.org/oldwiki/git.wiki.kernel.org/index.php/GitFaq.html#Can_I_add_empty_directories.3F):

> Currently the design of the Git index (staging area) only permits files to be listed

**Comment by nickfloyd** [comment] 2023-10-17 19:59
Hey @AshutoshBeta, just a quick follow up.  Please let us know if this Is this something that you are interested in following  up on and if what @kfcampbell posted was relevant? I’m going to close this but if you still need some help on this please feel free to reopen the issue. :heart: 

Thanks again for making things better for the community here! :heart:

**Closed by nickfloyd** 2023-10-17 19:59 UTC
Labels: Type: Bug, Type: Support
